name: Gary
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3172043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b090a'
    - '#5c4126'
    - '#816651'
    - '#b8b3af'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
