layout_spectrum: 0
typography_spectrum: 0.3172043
color:
  saturation: 0.3189618
  lightness: 0.1326378
  brandStrength: 0.2765359
  rhythmicContrast: 0.2533467
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Gary
